#!/bin/env bash
#
# Script allowing quick creation of a new project with place-holder content
#

if [ $# -ne 1 ]
then
    echo "usage: $0 <name>"
    exit 1
fi

name=$1

# replace spaces with '-'
name="${name// /-}"
# make lowercase
name="${name,,}"

# create hugo page, using the 'project' archetypes
hugo new $name.md -k project
# make a project solution(s) directory
mkdir -p src/$name
